version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cine_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cine_db
      # MYSQL_USER: cine_user
      # MYSQL_PASSWORD: cine_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
